# Generated by Django 5.0.4 on 2024-04-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_link', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='category',
            new_name='categories',
        ),
    ]
