# Generated by Django 5.0.4 on 2024-04-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_link', '0007_alter_channel_mentees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='price',
            field=models.DecimalField(null=True),
        ),
    ]
